Repository svnoak/PFW21, pull requests merged in 2021-05, with the labels that each got.

#56 Compare tables
  assets/css/style.css
  assets/javaScript/compare.js
  assets/javaScript/globals.js
  assets/javaScript/search.js
  search.html
Labels: Jämförelsesida

#67 Render favourites
  assets/javaScript/favorites.js
  favorites.html
Labels: Favoritersida, function

#69 Make saveBookmarked and addBookmarkToLS global function
  assets/javaScript/globals.js
Labels: global

#68 Make createProgrammeElement global function
  assets/javaScript/globals.js
  assets/javaScript/search.js
Labels: global

#70 Favoriter hämtas från LS och läggs till i listan för sökförslag
  assets/javaScript/compare.js
Labels: Jämförelsesida

#77 Removebookmarks on favouritesite
  assets/javaScript/favorites.js
  assets/javaScript/globals.js
  assets/javaScript/search.js
  assets/javaScript/svgs.js
  favorites.html
Labels: Favoritersida, function, global

#85 added video and attributes
  assets/javaScript/index.js
  assets/video/globe.mp4
Labels: design

#88 Set url parameter add to key
  assets/javaScript/compare.js
  assets/javaScript/detail.js
  assets/javaScript/globals.js
  assets/javaScript/index.js
  assets/javaScript/search.js
Labels: Söksida, function

#92 Sort and filter
  assets/css/style.css
  assets/javaScript/globals.js
  assets/javaScript/search.js
  search.html
Labels: Söksida, function

#93 Compare-site styling
  assets/css/style.css
  assets/javaScript/compare.js
  assets/javaScript/index.js
  assets/javaScript/svgs.js
Labels: Jämförelsesida

#91 New icons
  assets/css/style.css
  assets/javaScript/detail.js
  assets/javaScript/globals.js
  assets/javaScript/index.js
  assets/javaScript/svgs.js
Labels: design

#94 Bugfix search countries
  assets/javaScript/globals.js
  assets/javaScript/search.js
Labels: Söksida, bug

#99 adding countryname to search
  assets/javaScript/index.js
  assets/javaScript/search.js
Labels: Indexsida, function

#100 Bugfix icons
  assets/javaScript/favorites.js
  assets/javaScript/globals.js
  assets/javaScript/search.js
  assets/javaScript/svgs.js
Labels: bug, design

#102 Index css
  assets/css/footer.css
  assets/css/navbar.css
  assets/css/style.css
  assets/css/variables.css
  assets/javaScript/detail.js
  assets/javaScript/index.js
Labels: design

#106 Bugfix local storage
  assets/javaScript/compare.js
  assets/javaScript/globals.js
Labels: bug, global

#109 Update navbar.css
  assets/css/navbar.css
Labels: design

#110 Nya font-variabler för small och x-small
  assets/css/variables.css
Labels: design

#111 Ads
  assets/ads/annons_horizontell.jpg
  assets/ads/annons_kvadratisk.jpg
  assets/css/style.css
  assets/javaScript/globals.js
  assets/javaScript/index.js
Labels: function, global

#112 Detail styling
  assets/javaScript/detail.js
  assets/javaScript/globals.js
Labels: Detaljvy, design

#113 Färdig förslagslista och tabeller på jämförelsesidan
  assets/css/style.css
  assets/javaScript/compare.js
  assets/javaScript/svgs.js
Labels: Jämförelsesida

#116 Bugfix filter in urlparameters
  assets/javaScript/globals.js
  assets/javaScript/search.js
Labels: Söksida, bug

#120 Bugfix link to comparesite from bookmarksite
  assets/javaScript/favorites.js
  assets/javaScript/globals.js
  assets/javaScript/index.js
Labels: Indexsida, Jämförelsesida, bug

#127 Löste compare-sidan med nya render()
  assets/css/style.css
  assets/javaScript/compare.js
Labels: bug

#131 Search/css
  assets/css/style.css
  assets/javaScript/search.js
  search.html
Labels: Söksida, design

#133 Bugfix searchcss merge
  assets/css/style.css
  assets/javaScript/globals.js
  assets/javaScript/search.js
Labels: bug

#129 Favorites dialog styling
  assets/css/style.css
  assets/javaScript/globals.js
Labels: Favoritersida, design

#130 La till en text i sökresultatet i fall det inte finns några favoriter
  assets/javaScript/compare.js
Labels: Jämförelsesida

#134 Bugfix search
  assets/javaScript/search.js
Labels: Söksida, bug, function

#136 added circle through js instead
  assets/javaScript/search.js
  search.html
Labels: Söksida, bug, design

#138 Transition när söklistan öppnas på jämförelsesidan
  assets/css/style.css
  assets/javaScript/compare.js
Labels: Jämförelsesida, design

#137 Ingen horisontell scroll på karusellerna!!
  assets/css/style.css
  assets/javaScript/detail.js
  assets/javaScript/globals.js
  assets/javaScript/index.js
Labels: bug

#141 site titles updated
  assets/javaScript/detail.js
  favorites.html
  index.html
Labels: design, function

#147 Bugfix cityimages
  assets/javaScript/detail.js
Labels: bug, design

#149 Add earth
  .gitignore
  assets/css/style.css
  assets/javaScript/compare.js
  assets/javaScript/globals.js
  assets/video/globe.mp4
Labels: Indexsida, design

#150 removed unnessacary code that blocked the function
  assets/javaScript/compare.js
Labels: Jämförelsesida, bug

#151 Detail Finalized
  assets/css/style.css
  assets/javaScript/detail.js
Labels: Detaljvy, design

#153 change of paths
  assets/javaScript/detail.js
Labels: bug, design

#155 Site transitions
  assets/css/style.css
  assets/javaScript/compare.js
  assets/javaScript/detail.js
  assets/javaScript/favorites.js
  assets/javaScript/globals.js
  assets/javaScript/index.js
  assets/javaScript/search.js
Labels: design, global

#156 Updaterad: Bugfix compare plus icon
  assets/javaScript/compare.js
Labels: Jämförelsesida, bug

#160 New site transitions
  assets/css/style.css
  assets/javaScript/globals.js
Labels: bug

#171 change [brand]
  assets/javaScript/index.js
Labels: bug

#165 Favicon
  assets/javaScript/globals.js
  favicon.ico
Labels: design, global

#172 only show initial results when filter is present
  assets/javaScript/search.js
Labels: bug

#174 pills only added once
  assets/javaScript/search.js
Labels: bug

#175 made detail match figma
  assets/css/style.css
  assets/javaScript/detail.js
Labels: design

#177 add transition to deletion
  assets/css/style.css
  assets/javaScript/globals.js
Labels: Favoritersida, design

#180 saving search to sessionStorage
  assets/javaScript/search.js
Labels: Söksida, function

#186 fixade filter-overlayen
  assets/css/style.css
  assets/javaScript/search.js
Labels: Söksida, bug, design

#190 check if there is location.search already
  assets/javaScript/globals.js
  assets/javaScript/search.js
Labels: bug
